random_numbers <- rnorm(100, mean = 25, sd = 1)
print(random_numbers)
mean_value <- mean(random_numbers)
print(mean_value)
sd_value <- sd(random_numbers)
print(sd_value) 
print(paste("The Mean is", mean_value, "and the Standard Deviation is", sd_value))
